language: java
jdk: openjdk16
addons:
  sonarcloud:
    organization: akiwicoder
    token:
      secure: kfQRbIvTddi51Yfe6m2sN4TCpHF3VlxoZLG2wBBCu5yVH8xUH6IzcFVrpeJ29vYMHe+QLM7G94wqe5YPGeg0nZEIUfXBeZZqg1M3Hg/kSilUb4rMd0XQEhEm7Ifqq1i8lkY6ZtIaNVrUd1dU27QbHuoodIzQiOxQIAidAPSTs1Ms8HTAnDY/b5kDDA82/jPSl64VvnrSDg1wTDYVmp3MM+Ia+M/XfiNUH4pxrHLSTcra3AfyyyMvqRTMN2lvsFEMr6MS0ZsI/NXqFIW0rStgTu9a0moN8o2aAUS3d6wd7Eo2TOAWOS/a4pI5TTGx5UWBFB6JqhuUDVqJFAhZ5kRIemoNbd+rQEYetDRv/d6wV5qkABB+5xZSWiNnrAwFLa3aX5DUfcPXc/kFHVWK0AdrubRg0H5lM/tLsBXJEIsgbXAJyEX/Rh8AFN1whvNJ6FB6ZoGqNsBG9nwW+1UfOEvqBpthiY3dqdQVPkCxMr2Wv8iOpzpH+i/x39QcDrHXcdumuRUf8LdASIANi9yoxcSWyst2OJH2uUg4DXLWYn1YqsYizCBXQeAqMN+KxHG2iTG+hrKeBuiwqGNgu3FAdSYtyrWx+UCm8RJo0MrwST763CFsciC3ZlVbz7W0RN01lnME9+H92FapmF0mwK1wQEuzG+rUequeaNQO49a/YMSsYT8=
script:
- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=hecate-mud

