language: java
jdk: openjdk16
addons:
  sonarcloud:
    organization: akiwicoder
    token:
      secure: "OsV0XuiiT8yl0VtGF1od4KezruQ9KcFPs0B+3Yzz7PERbrUMOzmeeSzgrbvbZrBz2s4hGbn4h3eoYvhNBd0OIGbdkKSGR/pj57ujOB6jltzUpCSXUBLhHsoS5wsEDYdghlxjW7mGgu0nx+TchL40pJAWQICjpONPChjUvP2rEF5HaCy7pryIaPM0Sow5SQOu4buvdajr5ISaS2VpBS4xrXe0rcv40AD4pEZMl99sQwLoYswyd2Rb6YAQDf5Xr2mP/BUe6GvT/40zTVf6/twuRLtc4+F4IqB2McU9cyUVJjMRb+99RtUM35X/kw+RuIGPSWPcxd1VSWjnaiZWPyBdGoEp37j0JEOYCxoglRSBHp0EEGKBCspQcVB3U4AzJt66JwWhJYrxq2TugtsolB0sdS2WlCSqHno/WD397/j0tYCq5e2+JveAkhHhjUlod8nZ2I/AXM/B3U/ltZVjRpoBGIyFk4IVyTMpkHyijgbuh9nsz1lP6P8gd32DmVt4S1kTkY794F2Juo2eI0fStbvBx71jW0qmDNlz6kmqnJMHFzZOyh34hsrY9TU5E6BfPRLHjCYvgfKV9oaU7vhAt9fju4Cn04F7qNGnN1AvHpncEekaAkKDrhcelSe6+BzLJC9jSGa4xKDrhnr3O7fnCWzYWAF0Ax7rQbGyLR8wL2wiwdQ="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=hecate-mud